(() => {
  'use strict';
  const BUILD='20260820-income-truth-1';
  const arr=v=>Array.isArray(v)?v:[];
  const num=v=>{const n=Number(String(v??'').replace(/[£,%]/g,'').replace(/,/g,''));return Number.isFinite(n)?n:0};
  const ticker=v=>String(v||'').replace(/^LON:/i,'').replace(/\.L$/i,'').replace(/\..*$/,'').toUpperCase().trim();
  const accountCode=v=>{const s=String(v||'').toLowerCase();if(s.includes('212'))return'T212';if(/\big\b/.test(s)||s.includes('ig isa'))return'IG';const u=String(v||'').toUpperCase();return u==='IG'||u==='T212'?u:'CHECK'};
  const accountLabel=v=>accountCode(v)==='IG'?'IG ISA':accountCode(v)==='T212'?'Trading 212 ISA':'Account review';
  const parseDate=v=>{if(!v)return null;const raw=String(v).trim();const d=/^\d{4}-\d{2}-\d{2}/.test(raw)?new Date(`${raw.slice(0,10)}T12:00:00`):new Date(raw);return Number.isNaN(d.getTime())?null:d};
  const dateISO=d=>d instanceof Date&&!Number.isNaN(d.getTime())?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:'';
  const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
  function activeHoldings(state){return arr(state?.squad?.holdings).filter(h=>['ACTIVE','LOCKED'].includes(String(h?.status||'').toUpperCase())&&num(h?.shares)>0)}
  function incomeExempt(h){if(!h)return false;try{if(window.AuroraFinancialTruth?.isIncomeExempt)return Boolean(window.AuroraFinancialTruth.isIncomeExempt(h))}catch(_){}if(h.incomeExempt===true||h.dividendEligible===false)return true;const tk=ticker(h.ticker),ac=accountCode(h.account),reason=String(`${h.lockReason||''} ${h.role||''} ${h.source||''}`).toLowerCase();return tk==='TSCO'&&(ac==='CHECK'||/saye|save as you earn|2029|legacy/.test(reason))}
  function holdingAnnualIncome(h){try{if(window.AuroraFinancialTruth?.getHoldingAnnualIncome)return Math.max(0,num(window.AuroraFinancialTruth.getHoldingAnnualIncome(h)))}catch(_){}const shares=num(h?.shares),dps=num(h?.annualDpsGbp);return shares>0&&dps>0?shares*dps:Math.max(0,num(h?.annualIncomeGbp))}
  function holdingValue(h){const shares=num(h?.shares),live=num(h?.livePriceGbp);return shares>0&&live>0?shares*live:Math.max(0,num(h?.marketValueGbp))}
  function metrics(state){const holdings=activeHoldings(state),eligibleHoldings=holdings.filter(h=>!incomeExempt(h)),exemptHoldings=holdings.filter(incomeExempt),byAccount=new Map(),byTicker=new Map(),bySector=new Map();let annual=0,value=0,book=0;eligibleHoldings.forEach(h=>{const income=holdingAnnualIncome(h),mv=holdingValue(h),bc=Math.max(0,num(h.bookCostGbp)),ac=accountCode(h.account),tk=ticker(h.ticker),sector=String(h.sector||'Unclassified').trim()||'Unclassified';annual+=income;value+=mv;book+=bc;const a=byAccount.get(ac)||{account:ac,annual:0,value:0,book:0,positions:0};a.annual+=income;a.value+=mv;a.book+=bc;a.positions++;byAccount.set(ac,a);const t=byTicker.get(tk)||{ticker:tk,name:h.name||tk,annual:0,value:0,book:0,shares:0,accounts:new Set(),positions:0};t.annual+=income;t.value+=mv;t.book+=bc;t.shares+=num(h.shares);t.accounts.add(ac);t.positions++;byTicker.set(tk,t);bySector.set(sector,(bySector.get(sector)||0)+income)});const players=[...byTicker.values()].map(x=>({...x,accounts:[...x.accounts]})).sort((a,b)=>b.annual-a.annual||a.ticker.localeCompare(b.ticker));const accounts=[...byAccount.values()].sort((a,b)=>b.annual-a.annual);const sectors=[...bySector.entries()].map(([name,x])=>({name,annual:x})).sort((a,b)=>b.annual-a.annual);const monthly=annual/12,top5Annual=players.slice(0,5).reduce((s,x)=>s+x.annual,0);return{holdings,eligibleHoldings,exemptHoldings,annual,monthly,value,book,yoc:book>0?annual/book*100:0,yieldPct:value>0?annual/value*100:0,accounts,players,sectors,best:players[0]||null,top5Pct:annual>0?top5Annual/annual*100:0}}
  function holdingForEvent(state,e){const ac=accountCode(e?.account),tk=ticker(e?.ticker);return activeHoldings(state).filter(h=>!incomeExempt(h)).find(h=>accountCode(h.account)===ac&&ticker(h.ticker)===tk)||null}
  function eventAmount(state,e){const status=String(e?.status||'').toUpperCase(),actual=Math.max(0,num(e?.actualAmountGbp));if(status==='PAID'&&actual>0)return actual;const dps=Math.max(0,num(e?.dividendPerShareGbp)),eligible=Math.max(0,num(e?.sharesEligible));if(dps>0&&eligible>0)return dps*eligible;const h=holdingForEvent(state,e);if(h&&dps>0)return num(h.shares)*dps;return Math.max(0,num(e?.expectedAmountGbp))}
  function eventIncomeExempt(state,e){const h=activeHoldings(state).find(x=>accountCode(x.account)===accountCode(e?.account)&&ticker(x.ticker)===ticker(e?.ticker));return h?incomeExempt(h):false}
  function activeCalendar(state,events){const src=Array.isArray(events)?events:arr(state?.income?.calendar);return src.filter(e=>!['CANCELLED','ARCHIVED'].includes(String(e?.status||'').toUpperCase())&&!eventIncomeExempt(state,e))}
  function upcoming(state,events){const today=new Date();today.setHours(0,0,0,0);return activeCalendar(state,events).map(e=>({...e,computedAmount:eventAmount(state,e),__date:parseDate(e.payDate)})).filter(e=>e.__date&&e.__date>=today&&String(e.status||'').toUpperCase()!=='PAID').sort((a,b)=>a.__date-b.__date||ticker(a.ticker).localeCompare(ticker(b.ticker)))}
  function nextDividend(state,events){const e=upcoming(state,events)[0];return e?{ticker:ticker(e.ticker),name:e.name||ticker(e.ticker),account:accountCode(e.account),accountLabel:accountLabel(e.account),amount:Number(e.computedAmount.toFixed(2)),date:dateISO(e.__date),exDate:e.exDate||'',status:String(e.status||'FORECAST').toUpperCase()}:null}
  function calendarState(e){const status=String(e?.status||'FORECAST').toUpperCase();if(status==='CANCELLED'||status==='ARCHIVED')return'cancelled';if(status==='PAID')return'paid';const pay=parseDate(e?.payDate),today=new Date();today.setHours(0,0,0,0);if(pay&&pay<today)return'late';if(status==='CONFIRMED'||status==='ANNOUNCED')return'confirmed';return'forecast'}
  function reliability(state,events,m=metrics(state)){const all=Array.isArray(events)?events:arr(state?.income?.calendar),counts={paid:0,confirmed:0,forecast:0,late:0,cancelled:0};all.forEach(e=>counts[calendarState(e)]++);const players=new Set(m.players.map(p=>ticker(p.ticker)).filter(Boolean)),covered=new Set(all.filter(e=>calendarState(e)!=='cancelled').map(e=>ticker(e.ticker)).filter(t=>players.has(t)));return{all,counts,coveragePct:players.size?covered.size/players.size*100:0,coveredPlayers:covered.size,totalPlayers:players.size}}
  function runway(state,events,m=metrics(state)){const today=new Date();today.setHours(0,0,0,0);const end=new Date(today);end.setMonth(end.getMonth()+12);const first=new Date(today.getFullYear(),today.getMonth(),1,12);const months=[];for(let i=0;i<12;i++){const d=new Date(first.getFullYear(),first.getMonth()+i,1,12);months.push({key:monthKey(d),date:d,confirmed:0,forecast:0,total:0,confirmedCount:0,forecastCount:0})}const map=new Map(months.map(x=>[x.key,x]));let confirmed=0,forecast=0,receivedYtd=0;activeCalendar(state,events).forEach(e=>{const status=String(e?.status||'FORECAST').toUpperCase(),pay=parseDate(e.payDate),amount=eventAmount(state,e);if(status==='PAID'){if(pay&&pay.getFullYear()===today.getFullYear())receivedYtd+=amount;return}if(!pay||pay<today||pay>=end)return;const row=map.get(monthKey(pay));if(!row)return;if(status==='CONFIRMED'||status==='ANNOUNCED'){confirmed+=amount;row.confirmed+=amount;row.confirmedCount++}else{forecast+=amount;row.forecast+=amount;row.forecastCount++}row.total+=amount});const scheduled=confirmed+forecast,unscheduled=Math.max(0,m.annual-scheduled),mappedPct=m.annual>0?Math.min(100,scheduled/m.annual*100):0;return{months,confirmed,forecast,scheduled,unscheduled,mappedPct,receivedYtd}}
  function activeTransferIncome(state){const r=state?.transfer?.route;if(!r)return 0;const terminal=new Set(['REGISTERED','COMPLETE','COMPLETED','ARCHIVED','CANCELLED']);if(terminal.has(String(r.status||'').toUpperCase())||terminal.has(String(state?.mission?.status||'').toUpperCase()))return 0;return Math.max(0,num(r.expectedAnnualIncome??r.income))}
  function confirmedRegistrationUplift(state){const rows=[],seen=new Set();let total=0;arr(state?.transfer?.registrationDrafts).filter(r=>String(r?.status||'').toUpperCase()==='CONFIRMED').forEach(r=>{const key=String(r.transactionId||r.id||'');if(!key||seen.has(key))return;seen.add(key);const annual=Math.max(0,num(r.expectedAnnualIncomeGbp));total+=annual;rows.push({key,ticker:ticker(r.ticker),account:accountCode(r.account),annual})});return{total,count:rows.length,rows}}
  function historyForecast(history,targetMonthly){const rows=arr(history).filter(r=>num(r?.monthlyIncome)>0&&r?.at).map(r=>({at:new Date(r.at),monthly:num(r.monthlyIncome)})).filter(r=>!Number.isNaN(r.at.getTime())).sort((a,b)=>a.at-b.at);if(rows.length<2)return{ready:false,reason:'Needs more Income history'};const first=rows[0],last=rows.at(-1),days=Math.max(0,(last.at-first.at)/86400000);if(days<14||last.monthly<=first.monthly)return{ready:false,reason:days<14?'Needs 14+ days of history':'No positive observed pace yet'};const perDay=(last.monthly-first.monthly)/days,gap=Math.max(0,targetMonthly-last.monthly);if(gap<=0)return{ready:true,reached:true,paceMonthly30:perDay*30.4375,date:dateISO(last.at)};const daysNeeded=gap/perDay;if(!Number.isFinite(daysNeeded)||daysNeeded>3650)return{ready:false,reason:'Observed pace is too small for a useful estimate'};return{ready:true,reached:false,paceMonthly30:perDay*30.4375,date:dateISO(new Date(last.at.getTime()+daysNeeded*86400000)),daysNeeded}}
  function summary(state,events,history){const m=metrics(state),next=nextDividend(state,events),run=runway(state,events,m),rel=reliability(state,events,m),route=activeTransferIncome(state),reg=confirmedRegistrationUplift(state);return{version:1,build:BUILD,source:'SQUAD_CANONICAL',calculatedAt:new Date().toISOString(),annualIncomeGbp:Number(m.annual.toFixed(2)),monthlyIncomeGbp:Number(m.monthly.toFixed(2)),yieldOnCostPct:Number(m.yoc.toFixed(2)),portfolioYieldPct:Number(m.yieldPct.toFixed(2)),bestDividendPlayer:m.best?{ticker:m.best.ticker,name:m.best.name,annualIncomeGbp:Number(m.best.annual.toFixed(2))}:null,nextDividend:next,top5ConcentrationPct:Number(m.top5Pct.toFixed(2)),calendarCoveragePct:Number(rel.coveragePct.toFixed(2)),routeProjectedAnnualIncomeGbp:Number(route.toFixed(2)),confirmedRegistrationAnnualUpliftGbp:Number(reg.total.toFixed(2)),runway:{confirmedGbp:Number(run.confirmed.toFixed(2)),forecastGbp:Number(run.forecast.toFixed(2)),unscheduledAnnualGbp:Number(run.unscheduled.toFixed(2)),mappedPct:Number(run.mappedPct.toFixed(2)),receivedYtdGbp:Number(run.receivedYtd.toFixed(2))},forecast625:historyForecast(history,625),forecast2000:historyForecast(history,2000)}}
  window.AuroraIncomeTruth=Object.freeze({build:BUILD,num,ticker,accountCode,accountLabel,parseDate,dateISO,activeHoldings,incomeExempt,holdingAnnualIncome,metrics,eventAmount,activeCalendar,upcoming,nextDividend,calendarState,reliability,runway,activeTransferIncome,confirmedRegistrationUplift,historyForecast,summary});
})();