(() => {
  'use strict';
  const BUILD='20260827-system-health-1';
  const $=id=>document.getElementById(id);
  const num=v=>{const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
  const upper=v=>String(v||'').trim().toUpperCase();
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[ch]));
  const money=v=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',minimumFractionDigits:2,maximumFractionDigits:2}).format(num(v));
  const ago=iso=>{if(!iso)return'No timestamp';const t=new Date(iso).getTime();if(!Number.isFinite(t))return String(iso);const m=Math.max(0,Math.round((Date.now()-t)/60000));if(m<2)return'just now';if(m<60)return`${m} min ago`;const h=Math.round(m/60);if(h<48)return`${h} hr ago`;return`${Math.round(h/24)} d ago`};
  const stale=(iso,hours)=>{if(!iso)return true;const t=new Date(iso).getTime();return !Number.isFinite(t)||(Date.now()-t)>hours*3600000};
  const activeHolding=h=>!['SOLD','ARCHIVED','CLOSED','EXITED'].includes(upper(h?.status||'ACTIVE'))&&num(h?.shares)>0;
  function duplicateBills(state){const bills=(state.finance?.bills||[]).filter(b=>!['ARCHIVED','PAID','EXCLUDED','INACTIVE'].includes(upper(b.status))&&num(b.amount||b.value)>0);const m=new Map();bills.forEach(b=>{const name=String(b.name||b.label||b.bill||'').toLowerCase().replace(/\s+/g,' ').trim(),amount=num(b.amount||b.value).toFixed(2),freq=upper(b.frequency||b.cadence||'');const k=`${name}|${amount}|${freq}`;m.set(k,(m.get(k)||0)+1)});return [...m.values()].filter(n=>n>1).reduce((s,n)=>s+n-1,0)}
  function chairmanOpen(state){return (state.transfer?.chairmanOffers||[]).filter(o=>!['WITHDRAWN','EXPIRED','COMPLETE','CLOSED'].includes(upper(o.status))).length}
  function squadMetrics(state){const rows=(state.squad?.holdings||[]).filter(activeHolding);const market=rows.reduce((s,h)=>s+Math.max(0,num(h.marketValueGbp)||num(h.shares)*num(h.livePriceGbp)),0),book=rows.reduce((s,h)=>s+Math.max(0,num(h.bookCostGbp)),0),annual=rows.reduce((s,h)=>s+Math.max(0,num(h.annualIncomeGbp)||num(h.shares)*num(h.annualDpsGbp)),0);return{rows,market,book,annual,pnl:market-book}}
  function checks(state){
    const f=state.finance||{},mission=state.transfer?.mission,route=state.transfer?.route,plan=state.scouting?.allocationPlan,receipts=state.registration?.receipts||[],sq=squadMetrics(state),missionStatus=upper(mission?.status||'NONE');
    const routeRows=[...(route?.allocations||[]),...(route?.brokerCashAllocations||[])],receiptCount=mission?receipts.filter(r=>String(r.missionId||'')===String(mission.id||'')).length:0,dup=duplicateBills(state),offers=chairmanOpen(state),squadAge=state.squad?.importedAt||state.squad?.updatedAt||state.squad?.lastRefreshAt;
    const financeStatus=!f.stage5PaydayDecision?'attention':dup?'attention':'healthy';
    const scoutBrokerUnresolved=(state.scouting?.candidates||[]).filter(c=>['PASS','CAUTION','WATCH','APPROVED'].includes(upper(c.status||c.verdict||c.signal))&&!String(c.account||c.broker||c.preferredBroker||c.platform||'').trim()).length;
    const scoutingStatus=mission&&num(mission.budget)>0&&!plan?.allocations?.length?'blocked':scoutBrokerUnresolved?'attention':'healthy';
    const transferStatus=missionStatus==='CANCELLED'?'attention':mission&&plan?.allocations?.length&&!route?.locked?'attention':route?.locked?'healthy':'healthy';
    const registrationStatus=route?.locked&&receiptCount<routeRows.length?'attention':missionStatus==='COMPLETE'?'healthy':'healthy';
    const squadStatus=!sq.rows.length?'blocked':stale(squadAge,24)?'stale':'healthy';
    const incomeStatus=!sq.rows.length?'blocked':sq.annual<=0?'attention':'healthy';
    const finance={key:'finance',name:'Finance',href:'finance.html',status:financeStatus,summary:financeStatus==='healthy'?'Cash truth and payday calculations are coherent.':dup?`${dup} duplicate bill record${dup===1?'':'s'} need review.`:'Payday Stage 5 has not been proved yet.',metrics:[['SAFE RELEASE',money(f.stage5PaydayDecision?.maximumSafeRelease||0)],['ACTIVE BILLS',String((f.bills||[]).filter(b=>!['ARCHIVED','PAID','EXCLUDED','INACTIVE'].includes(upper(b.status))).length)],['HOLDING POT',money(f.stage3HoldingPot?.currentBalance??f.holdingPotBalance)],['DUPLICATES',String(dup)]]};
    const scouting={key:'scouting',name:'Scouting',href:'scouting.html',status:scoutingStatus,summary:scoutingStatus==='blocked'?'Finance has released money but no Scouting allocation plan is ready.':scoutBrokerUnresolved?`${scoutBrokerUnresolved} candidate broker route${scoutBrokerUnresolved===1?'':'s'} need evidence.`:'Candidate and allocation state is ready for the current chain.',metrics:[['CANDIDATES',String((state.scouting?.candidates||[]).length)],['PLAN',upper(plan?.status||'WAITING')],['ALLOCATIONS',String(plan?.allocations?.length||0)],['BROKER CHECKS',String(scoutBrokerUnresolved)]]};
    const transfer={key:'transfer',name:'Transfer',href:'transfer.html',status:transferStatus,summary:missionStatus==='CANCELLED'?'Previous Finance mission is cancelled; a new release is required.':route?.locked?'Route is frozen for Registration.':mission?'Mission exists and is waiting for the next chain step.':'No live payday mission; Chairman reviews remain independent.',metrics:[['MISSION',missionStatus],['BUDGET',money(mission?.budget||0)],['ROUTE',route?.locked?'LOCKED':routeRows.length?'READY':'WAITING'],['CHAIRMAN CASES',String(offers)]]};
    const registration={key:'registration',name:'Registration',href:'registration.html',status:registrationStatus,summary:route?.locked&&receiptCount<routeRows.length?`${routeRows.length-receiptCount} locked execution${routeRows.length-receiptCount===1?'':'s'} still need broker confirmation.`:missionStatus==='COMPLETE'?'Current mission has been settled.':'No incomplete locked execution is blocking the chain.',metrics:[['ROUTE LEGS',String(routeRows.length)],['RECEIPTS',String(receiptCount)],['MISSION',missionStatus],['SETTLED',route?.settled?'YES':'NO']]};
    const squad={key:'squad',name:'Squad Hub',href:'squad.html',status:squadStatus,summary:!sq.rows.length?'No active clean holdings are available.':squadStatus==='stale'?`Live holding snapshot is ${ago(squadAge)}.`:'Holdings and market snapshot are current.',metrics:[['POSITIONS',String(sq.rows.length)],['MARKET VALUE',money(sq.market)],['P/L',`${sq.pnl>=0?'+':''}${money(sq.pnl)}`],['REFRESH',ago(squadAge)]]};
    const income={key:'income',name:'Income',href:'income.html',status:incomeStatus,summary:incomeStatus==='blocked'?'Income cannot calculate without Squad holdings.':incomeStatus==='attention'?'Holdings exist but no forward annual income is recorded.':'Forward dividend run-rate is populated from the clean Squad.',metrics:[['ANNUAL',money(sq.annual)],['MONTHLY',money(sq.annual/12)],['TARGET',money(24000)],['PROGRESS',`${Math.min(100,sq.annual/24000*100).toFixed(1)}%`]]};
    return{cards:[finance,scouting,transfer,registration,squad,income],dup,offers,squadAge,missionStatus};
  }
  function severity(cards){if(cards.some(c=>c.status==='blocked'))return'blocked';if(cards.some(c=>c.status==='stale'))return'stale';if(cards.some(c=>c.status==='attention'))return'attention';return'good'}
  function alerts(c){const out=[];c.cards.forEach(card=>{if(card.status==='healthy')return;out.push({tone:card.status==='blocked'||card.status==='stale'?'bad':'warn',title:`${card.name}: ${upper(card.status)}`,detail:card.summary,href:card.href})});if(!out.length)out.push({tone:'good',title:'No active system warnings',detail:'All monitored clean-rebuild departments are currently coherent.',href:''});return out}
  function render(){const A=window.AuroraClean;if(!A)return;const state=A.readState(),c=checks(state),sev=severity(c.cards),list=alerts(c),healthy=c.cards.filter(x=>x.status==='healthy').length,attention=c.cards.filter(x=>x.status==='attention').length,blocked=c.cards.filter(x=>x.status==='blocked'||x.status==='stale').length;
    const master=$('systemHealthMaster');if(master){master.className=`health-master ${sev}`;master.innerHTML=`<div class="health-kicker">AURORA SYSTEM HEALTH</div><h2>${sev==='good'?'ALL SYSTEMS HEALTHY':sev==='attention'?'ATTENTION REQUIRED':sev==='stale'?'STALE DATA DETECTED':'CHAIN BLOCKED'}</h2><p class="health-master-copy">One read-only view of the clean Finance → Scouting → Transfer → Registration → Squad → Income chain.</p><div class="health-master-grid"><div class="health-master-stat"><span>HEALTHY</span><strong>${healthy}</strong></div><div class="health-master-stat"><span>ATTENTION</span><strong>${attention}</strong></div><div class="health-master-stat"><span>BLOCKED / STALE</span><strong>${blocked}</strong></div><div class="health-master-stat"><span>OPEN CHAIRMAN CASES</span><strong>${c.offers}</strong></div></div>`}
    const alertHost=$('systemHealthAlerts');if(alertHost)alertHost.innerHTML=`<div class="health-kicker">ACTION CENTRE</div><h3>${list.length} live item${list.length===1?'':'s'}</h3><div class="health-alert-list">${list.map(a=>`<div class="health-alert ${a.tone}"><span class="health-alert-dot"></span><div><strong>${esc(a.title)}</strong><small>${esc(a.detail)}</small></div>${a.href?`<a href="${a.href}">Open →</a>`:''}</div>`).join('')}</div>`;
    const grid=$('systemHealthGrid');if(grid)grid.innerHTML=c.cards.map(card=>`<article class="health-card ${card.status}"><div class="health-card-head"><div><div class="health-kicker">DEPARTMENT</div><h3>${esc(card.name)}</h3><p>${esc(card.summary)}</p></div><span class="health-status ${card.status}">${upper(card.status)}</span></div><div class="health-card-metrics">${card.metrics.map(([k,v])=>`<div class="health-card-metric"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div><div class="health-card-footer"><small>Clean-state authority</small><a href="${card.href}">Open ${esc(card.name)} →</a></div></article>`).join('');
    const updated=$('systemHealthUpdated');if(updated)updated.textContent=`Updated ${new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}`;
  }
  function boot(){if(!window.AuroraClean){setTimeout(boot,60);return}render();window.addEventListener('aurora-clean:state',render);window.addEventListener('aurora:market-prices',render);window.addEventListener('pageshow',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});window.AuroraSystemHealth=Object.freeze({BUILD,render,checks})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();